# Generated by Django 3.1.2 on 2020-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelevelplans',
            name='count',
            field=models.IntegerField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
