# Generated by Django 3.1.2 on 2020-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_corelevelplans_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilate',
            name='total_pv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affilate',
            name='total_teams',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
