# Generated by Django 3.1.2 on 2021-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201221_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelevelplans',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
