# Generated by Django 3.1.2 on 2021-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_corelevelplans_joining_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelevelplans',
            name='has_purchase_bonus',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='corelevelplans',
            name='purchase_bonus',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='corelevelplans',
            name='joining_pv',
            field=models.IntegerField(blank=True, default=0, help_text='the joining credit award package', null=True),
        ),
    ]
