# Generated by Django 3.1.2 on 2021-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rank_total_pv_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='total_pv_count',
            new_name='total_pv_count_end',
        ),
        migrations.AddField(
            model_name='rank',
            name='total_pv_count_start',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
