# Generated by Django 3.1.2 on 2021-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210228_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='based_on',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='direct_referrals',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='downline_value',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='level_no',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='total_member_on_level',
        ),
    ]
