# Generated by Django 3.1.2 on 2021-03-04 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_corelevelplans_repurchase_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepurchaseBonusLevel',
            fields=[
                ('level_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level1_percentage', models.FloatField(blank=True, default=0.0, help_text='First core level', null=True)),
                ('level2_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level3_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level4_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level5_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level6_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level7_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level8_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level9_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level10_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level11_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level12_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level13_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level14_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level15_percentage', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='corelevelplans',
            name='repurchase_bonus',
        ),
        migrations.AddField(
            model_name='corelevelplans',
            name='repurchase_bonus_percent',
            field=models.IntegerField(blank=True, default=0, help_text='Percentage or repurchase bonus goes here.', null=True),
        ),
        migrations.AddField(
            model_name='corelevelplans',
            name='repurchase_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.repurchasebonuslevel'),
        ),
    ]
