# Generated by Django 3.1.2 on 2021-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210304_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corelevelplans',
            name='repurchase_bonus_percent',
        ),
        migrations.AddField(
            model_name='corelevelplans',
            name='is_repurchase',
            field=models.BooleanField(default=False),
        ),
    ]
