# Generated by Django 3.0.4 on 2020-11-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=800, null=True)),
                ('store_desc', models.TextField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorLevelPlans',
            fields=[
                ('core_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=500, null=True)),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='plan/image/')),
                ('show_plan_form', models.BooleanField(default=False)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('level1_percentage', models.FloatField(blank=True, default=0.0, help_text='First core level', null=True)),
                ('level2_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level3_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level4_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level5_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level6_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level7_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level8_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level9_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level10_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level11_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level12_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level13_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level14_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level15_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
        ),
    ]
