# Generated by Django 3.1.2 on 2021-02-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=800, null=True)),
                ('store_desc', models.TextField(blank=True, null=True)),
                ('store_cover', models.ImageField(blank=True, null=True, upload_to='store/image')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenodrGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venodr/gallery')),
                ('img_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorLevelPlans',
            fields=[
                ('core_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=500, null=True)),
                ('show_plan_form', models.BooleanField(default=False)),
                ('purchase_bonus', models.FloatField(blank=True, help_text='bonus amount', null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('level1_percentage', models.FloatField(blank=True, default=0.0, help_text='First core level', null=True)),
                ('level2_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level3_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level4_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level5_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level6_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level7_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level8_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level9_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level10_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level11_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level12_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level13_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level14_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('level15_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_gallery',
            field=models.ManyToManyField(blank=True, to='vendors.VenodrGallery'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('core_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], default='pen', max_length=10)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_core_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
