# Generated by Django 3.1.2 on 2021-02-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0007_auto_20210210_1223'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_marketing.billinginfo'),
        ),
    ]
