# Generated by Django 3.1.2 on 2021-02-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_order_billing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
