# Generated by Django 3.1.2 on 2020-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_store_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlevelplans',
            name='purchase_bonus',
            field=models.FloatField(blank=True, help_text='bonus amount', null=True),
        ),
    ]
