# Generated by Django 3.1.2 on 2020-12-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendorlevelplans_plan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='purchase_bonus',
        ),
    ]
