# Generated by Django 3.1.2 on 2021-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210213_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlevelplans',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
