# Generated by Django 3.1.2 on 2020-12-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorlevelplans_purchase_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlevelplans',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
