# Generated by Django 3.1.2 on 2021-02-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0003_remove_products_product_brand'),
        ('vendors', '0007_auto_20210214_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.products'),
        ),
    ]
