# Generated by Django 3.1.2 on 2021-01-02 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0007_auto_20201211_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('core_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], max_length=10)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
