# Generated by Django 3.1.2 on 2021-01-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0003_auto_20201204_0703'),
        ('vendors', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.products'),
        ),
    ]
