# Generated by Django 3.1.2 on 2021-02-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20210214_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_desc', models.TextField(null=True)),
                ('video_url', models.URLField(max_length=300, verbose_name='')),
                ('store_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
