# Generated by Django 3.1.2 on 2021-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20210221_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='store_desc',
        ),
    ]
