# Generated by Django 3.1.2 on 2021-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], default='pen', max_length=10),
        ),
    ]
