# Generated by Django 3.1.2 on 2021-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_remove_vendor_store_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=100)),
                ('social_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vendordata',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='images',
            field=models.ImageField(null=True, upload_to='about/image'),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='social',
            field=models.ManyToManyField(blank=True, to='vendors.Social'),
        ),
    ]
