# Generated by Django 3.1.2 on 2021-02-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20210221_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordata',
            old_name='social',
            new_name='social_net',
        ),
    ]
