# Generated by Django 3.1.2 on 2021-02-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20210221_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordata',
            name='images',
        ),
        migrations.CreateModel(
            name='VendorCeoImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_img', models.ImageField(null=True, upload_to='about/ceo/image')),
                ('store_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendordata',
            name='images',
            field=models.ManyToManyField(blank=True, to='vendors.VendorCeoImgs'),
        ),
    ]
