# Generated by Django 3.1.2 on 2021-02-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_auto_20210221_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
