# Generated by Django 3.1.2 on 2021-02-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_social_icon_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorceoimgs',
            name='store_name',
        ),
    ]
