# Generated by Django 3.1.2 on 2021-02-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_remove_vendorceoimgs_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordata',
            name='store_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
