# Generated by Django 3.1.2 on 2021-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_auto_20210222_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='social_link',
            field=models.URLField(max_length=300, null=True, verbose_name='social_link'),
        ),
    ]
