# Generated by Django 3.1.2 on 2021-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_social_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='promotions')),
                ('size', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vendordata',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='vendors.Promotions'),
        ),
    ]
