# Generated by Django 3.1.2 on 2021-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_auto_20210224_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_no',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
