# Generated by Django 3.1.2 on 2021-02-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0004_paymenttype'),
        ('vendors', '0020_order_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.paymenttype'),
        ),
    ]
