# Generated by Django 3.1.2 on 2021-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
