# Generated by Django 3.1.2 on 2021-03-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210307_1305'),
        ('vendors', '0022_auto_20210228_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level10_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level11_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level12_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level13_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level14_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level15_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level1_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level2_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level3_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level4_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level5_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level6_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level7_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level8_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='level9_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorlevelplans',
            name='show_plan_form',
        ),
        migrations.AddField(
            model_name='vendorlevelplans',
            name='linked_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans'),
        ),
    ]
