# Generated by Django 3.1.2 on 2021-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_auto_20210307_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_already',
            field=models.BooleanField(default=False),
        ),
    ]
