# Generated by Django 3.1.2 on 2021-02-07 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingCarousel',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='landing/car')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('pcat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_cat_name', models.CharField(max_length=500)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat_decs', models.TextField(blank=True, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='pcat-image/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prod/images/')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=800)),
                ('product_desc', models.TextField(null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('selling_price', models.BigIntegerField(null=True)),
                ('dealer_price', models.BigIntegerField(null=True)),
                ('business_value', models.BigIntegerField(help_text='PV', null=True)),
                ('discount', models.FloatField(default=0.0, null=True)),
                ('stock_amount', models.BigIntegerField(default=1, null=True)),
                ('tax', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_cat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=500, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.category')),
            ],
        ),
    ]
