# Generated by Django 3.0.4 on 2020-11-29 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_marketing', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('pcat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_cat_name', models.CharField(max_length=500)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_marketing.CoreBrand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prod/images/')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_cat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=500, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=800)),
                ('product_desc', models.TextField(null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('selling_price', models.BigIntegerField(null=True)),
                ('dealer_price', models.BigIntegerField(null=True)),
                ('business_value', models.BigIntegerField(help_text='PV')),
                ('discount', models.FloatField(default=0.0)),
                ('stock_amount', models.BigIntegerField(default=1)),
                ('tax', models.FloatField(default=0.0)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_marketing.CoreBrand')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.Category')),
                ('product_images', models.ManyToManyField(blank=True, to='core_ecommerce.ProductImage')),
                ('product_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.ParentCategory')),
                ('product_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.SubCategory')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
                ('vendor_plans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.VendorLevelPlans')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.ParentCategory'),
        ),
    ]
