# Generated by Django 3.1.2 on 2020-12-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ManyToManyField(to='core_ecommerce.ProductImage'),
        ),
    ]
