# Generated by Django 3.1.2 on 2020-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0002_auto_20201202_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='business_value',
            field=models.BigIntegerField(help_text='PV', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ManyToManyField(blank=True, to='core_ecommerce.ProductImage'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_amount',
            field=models.BigIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
