# Generated by Django 3.1.2 on 2021-01-16 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0003_auto_20201204_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingCarousel',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='landing/car')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
