# Generated by Django 3.1.2 on 2021-02-28 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0003_remove_products_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
