# Generated by Django 3.1.2 on 2021-01-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0004_landingcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='pcat-image/'),
        ),
    ]
