# Generated by Django 3.1.2 on 2021-01-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0005_parentcategory_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='cat_decs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
