# Generated by Django 3.0.4 on 2020-11-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBrand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=500)),
                ('brand_description', models.TextField(null=True)),
                ('brand_image', models.ImageField(null=True, upload_to='brand-pics/')),
            ],
        ),
        migrations.CreateModel(
            name='UnilevelNetworkLayer',
            fields=[
                ('layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnilevelNetwork',
            fields=[
                ('network_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affilate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Affilate')),
                ('links', models.ManyToManyField(blank=True, to='core_marketing.UnilevelNetworkLayer')),
                ('marketing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CoreLevelPlans')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_name', models.CharField(max_length=700)),
                ('reward_based_on', models.CharField(choices=[('maint', 'Main Target'), ('downt', 'Downline Target')], max_length=6)),
                ('count_based_on', models.CharField(choices=[('pvval', 'Pv Value'), ('memcnt', 'Members Count')], max_length=6)),
                ('duration', models.BigIntegerField(default=0)),
                ('downline_value', models.BigIntegerField(blank=True, null=True)),
                ('direct_referrals', models.BigIntegerField(blank=True, null=True)),
                ('level_no', models.IntegerField(blank=True, null=True)),
                ('total_member_on_level', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CoreLevelPlans')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutReport',
            fields=[
                ('payout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('admin_fee', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('net_amount', models.IntegerField()),
                ('mode', models.CharField(max_length=50)),
                ('account_detail', models.TextField()),
                ('status', models.CharField(choices=[('cmp', 'Completed'), ('pen', 'Pending'), ('can', 'Cancelled')], max_length=5)),
                ('transaction_detail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositReport',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('bnk', 'Bank')], max_length=5)),
                ('status', models.CharField(choices=[('cmp', 'Completed'), ('pen', 'Pending'), ('can', 'Cancelled')], max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
