# Generated by Django 3.1.2 on 2021-02-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_affilate_parent'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBrand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=500)),
                ('brand_description', models.TextField(null=True)),
                ('brand_image', models.ImageField(null=True, upload_to='brand-pics/')),
            ],
        ),
        migrations.CreateModel(
            name='CoreDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doc', models.FileField(upload_to='core/docs')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnilevelNetwork',
            fields=[
                ('layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affilate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate')),
                ('marketing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestNetwork',
            fields=[
                ('layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affilate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate')),
                ('marketing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core_marketing.testnetwork')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_name', models.CharField(max_length=700)),
                ('reward_based_on', models.CharField(choices=[('maint', 'Main Target'), ('downt', 'Downline Target')], max_length=6)),
                ('count_based_on', models.CharField(choices=[('pvval', 'Pv Value'), ('memcnt', 'Members Count')], max_length=6)),
                ('duration', models.BigIntegerField(default=0)),
                ('downline_value', models.BigIntegerField(blank=True, null=True)),
                ('direct_referrals', models.BigIntegerField(blank=True, null=True)),
                ('level_no', models.IntegerField(blank=True, null=True)),
                ('total_member_on_level', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutReport',
            fields=[
                ('payout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('admin_fee', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('net_amount', models.IntegerField()),
                ('mode', models.CharField(max_length=50)),
                ('account_detail', models.TextField()),
                ('status', models.CharField(choices=[('cmp', 'Completed'), ('pen', 'Pending'), ('can', 'Cancelled')], max_length=5)),
                ('transaction_detail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositReport',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('bnk', 'Bank')], max_length=5)),
                ('status', models.CharField(choices=[('cmp', 'Completed'), ('pen', 'Pending'), ('can', 'Cancelled')], max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoreTestMpttNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_marketing.coretestmpttnode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffilatePlans',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('core', 'Core Plans'), ('ven', 'Vendor Plan')], max_length=5, null=True)),
                ('total_earned', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_downline', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_direct_referrals', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_earned_pv', models.BigIntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affilate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate')),
                ('core_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
                ('vendor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlevelplans')),
            ],
        ),
    ]
