# Generated by Django 3.1.2 on 2020-12-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unilevelnetworklayer',
            name='user',
        ),
        migrations.DeleteModel(
            name='UnilevelNetwork',
        ),
        migrations.DeleteModel(
            name='UnilevelNetworkLayer',
        ),
    ]
