# Generated by Django 3.1.2 on 2020-12-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorlevelplans_purchase_bonus'),
        ('core_marketing', '0003_unilevelnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='vendor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlevelplans'),
        ),
    ]
