# Generated by Django 3.1.2 on 2021-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0003_coretestmpttnode_affilate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coretestmpttnode',
            name='affilate',
        ),
    ]
