# Generated by Django 3.1.2 on 2021-02-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_affilate_parent'),
        ('core_ecommerce', '0002_auto_20210207_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('core_marketing', '0004_remove_coretestmpttnode_affilate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreVendorMlmOrders',
            fields=[
                ('core_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], default='pen', max_length=10)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='CoreMlmOrders',
            fields=[
                ('core_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], default='pen', max_length=10)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
            ],
        ),
    ]
