# Generated by Django 3.1.2 on 2020-12-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_full_name'),
        ('core_marketing', '0004_auto_20201206_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='marketing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans'),
        ),
    ]
