# Generated by Django 3.1.2 on 2021-02-10 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0005_coremlmorders_corevendormlmorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('binfo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('address', models.TextField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
    ]
