# Generated by Django 3.1.2 on 2020-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0006_unilevelnetwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='level',
            field=models.IntegerField(blank=True, help_text='network level count', null=True),
        ),
    ]
