# Generated by Django 3.1.2 on 2020-12-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_corelevelplans_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_marketing', '0007_auto_20201206_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unilevelnetwork',
            old_name='layer_id',
            new_name='network_id',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='level',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='vendor_plan',
        ),
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='affilate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate'),
        ),
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='marketing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans'),
        ),
        migrations.CreateModel(
            name='UnilevelNetworkLayer',
            fields=[
                ('layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='unilevelnetwork',
            name='links',
            field=models.ManyToManyField(blank=True, to='core_marketing.UnilevelNetworkLayer'),
        ),
    ]
