# Generated by Django 3.1.2 on 2021-02-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0008_remove_coremlmorders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
