# Generated by Django 3.1.2 on 2020-12-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_marketing', '0008_auto_20201206_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unilevelnetwork',
            old_name='network_id',
            new_name='layer_id',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='affilate',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='links',
        ),
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='marketing_plan',
        ),
        migrations.AddField(
            model_name='unilevelnetwork',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unilevelnetwork',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UnilevelNetworkLayer',
        ),
    ]
