# Generated by Django 3.1.2 on 2020-12-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_corelevelplans_count'),
        ('core_marketing', '0009_auto_20201206_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='unilevelnetwork',
            name='affilate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate'),
        ),
    ]
