# Generated by Django 3.1.2 on 2020-12-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_corelevelplans_count'),
        ('core_marketing', '0010_unilevelnetwork_affilate'),
    ]

    operations = [
        migrations.AddField(
            model_name='unilevelnetwork',
            name='marketing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans'),
        ),
    ]
