# Generated by Django 3.1.2 on 2021-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0011_auto_20210210_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremlmorders',
            name='paid_already',
            field=models.BooleanField(default=False),
        ),
    ]
