# Generated by Django 3.1.2 on 2020-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0011_unilevelnetwork_marketing_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilevelnetwork',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
