# Generated by Django 3.1.2 on 2020-12-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0012_auto_20201206_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unilevelnetwork',
            name='level',
        ),
    ]
