# Generated by Django 3.1.2 on 2021-02-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20210214_2100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_marketing', '0014_auto_20210211_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreVendorTestMpttNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('marketing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlevelplans')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_marketing.corevendortestmpttnode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
