# Generated by Django 3.1.2 on 2020-12-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_corelevelplans_count'),
        ('vendors', '0006_vendorlevelplans_purchase_bonus'),
        ('core_marketing', '0014_affilateplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilateplans',
            name='core_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans'),
        ),
        migrations.AddField(
            model_name='affilateplans',
            name='plan_type',
            field=models.CharField(choices=[('core', 'Core Plans'), ('ven', 'Vendor Plan')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='affilateplans',
            name='vendor_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlevelplans'),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='affilate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate'),
        ),
    ]
