# Generated by Django 3.1.2 on 2021-02-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20210214_2100'),
        ('core_marketing', '0015_corevendortestmpttnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevendormlmorders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlevelplans'),
        ),
    ]
