# Generated by Django 3.1.2 on 2021-02-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_marketing', '0016_auto_20210217_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevendormlmorders',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vsponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corevendormlmorders',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
