# Generated by Django 3.1.2 on 2020-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0017_auto_20201212_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilateplans',
            name='total_direct_referrals',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affilateplans',
            name='total_downline',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affilateplans',
            name='total_earned',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affilateplans',
            name='total_earned_pv',
            field=models.BigIntegerField(null=True),
        ),
    ]
