# Generated by Django 3.1.2 on 2021-02-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0017_auto_20210217_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevendormlmorders',
            name='ordered_from',
        ),
    ]
