# Generated by Django 3.1.2 on 2021-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0018_remove_corevendormlmorders_ordered_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretestmpttnode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='corevendortestmpttnode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
