# Generated by Django 3.1.2 on 2020-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0018_auto_20201221_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilateplans',
            name='total_direct_referrals',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_downline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_earned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_earned_pv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
