# Generated by Django 3.1.2 on 2021-02-24 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0019_auto_20210218_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMarketingSetting',
            fields=[
                ('core_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pv_rate_etb', models.BigIntegerField(default=0, help_text='This is the pv exhange rate for ETB')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
