# Generated by Django 3.1.2 on 2020-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0019_auto_20201221_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilateplans',
            name='total_direct_referrals',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_downline',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_earned',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='affilateplans',
            name='total_earned_pv',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
