# Generated by Django 3.1.2 on 2021-02-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0020_coremarketingsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremarketingsetting',
            name='final',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
