# Generated by Django 3.1.2 on 2021-01-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210102_1216'),
        ('core_marketing', '0021_testnetwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnetwork',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testnetwork',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='testnetwork',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='testnetwork',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='testnetwork',
            name='affilate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate'),
        ),
    ]
