# Generated by Django 3.1.2 on 2021-01-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0022_auto_20210107_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNetwork',
        ),
    ]
