# Generated by Django 3.1.2 on 2021-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0022_auto_20210224_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingwallet',
            name='pv_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='marketingwallet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
