# Generated by Django 3.1.2 on 2021-01-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_affilate_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_marketing', '0023_delete_testnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNetwork',
            fields=[
                ('layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affilate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate')),
                ('marketing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corelevelplans')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
