# Generated by Django 3.1.2 on 2021-02-28 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210228_0913'),
        ('core_marketing', '0024_auto_20210228_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardsReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rew', 'Rewarded'), ('pen', 'Pending'), ('can', 'Cancelled')], max_length=5)),
                ('affilate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_marketing.rewards')),
            ],
        ),
    ]
