# Generated by Django 3.1.2 on 2021-01-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_affilate_parent'),
        ('core_marketing', '0024_testnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnetwork',
            name='affilate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='accounts.affilate'),
        ),
    ]
