# Generated by Django 3.1.2 on 2021-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0025_rewardsreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardsreport',
            name='status',
            field=models.CharField(choices=[('rew', 'Rewarded'), ('pen', 'Pending'), ('can', 'Cancelled')], default='pen', max_length=5),
        ),
    ]
