# Generated by Django 3.1.2 on 2021-01-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_affilate_parent'),
        ('core_marketing', '0025_auto_20210107_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnetwork',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core_marketing.testnetwork'),
        ),
        migrations.AlterField(
            model_name='testnetwork',
            name='affilate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.affilate'),
        ),
    ]
