# Generated by Django 3.1.2 on 2021-02-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0004_paymenttype'),
        ('core_marketing', '0026_auto_20210228_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremlmorders',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.paymenttype'),
        ),
        migrations.AddField(
            model_name='coremlmorders',
            name='reference_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='corevendormlmorders',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_ecommerce.paymenttype'),
        ),
        migrations.AddField(
            model_name='corevendormlmorders',
            name='reference_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
