# Generated by Django 3.1.2 on 2021-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0027_auto_20210228_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretestmpttnode',
            name='parent_earning',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
