# Generated by Django 3.1.2 on 2021-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0027_usermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doc', models.FileField(upload_to='core/docs')),
            ],
        ),
    ]
