# Generated by Django 3.1.2 on 2021-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketing', '0028_coretestmpttnode_parent_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coretestmpttnode',
            old_name='parent_earning',
            new_name='parent_earning_etb',
        ),
        migrations.AddField(
            model_name='coretestmpttnode',
            name='parent_earning_pv',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
